name: reusable-workflow-build-patch-package

on:
  workflow_call:
    inputs:
      repository:
        type: string
        description: Repository name
        required: true

# Use the Bash shell as default settings for all jobs in the workflow
defaults:
  run:
    shell: bash

jobs:
  build-patch-package:
    name: Build Patch Package
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout main branch of ${{ inputs.repository }} repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: main
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ vars.PYTHON_VERSION_VAR }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ vars.POETRY_VERSION_VAR }}

      - name: Set environment variables
        run: |
          echo "CURRENT_VERSION=$(poetry version --dry-run -s)" >> $GITHUB_ENV
          echo "PATCH_VERSION=$(poetry version patch --dry-run -s)" >> $GITHUB_ENV

      - name: Bump package version to ${{ env.PATCH_VERSION }}
        run: |
          poetry self add poetry-bumpversion
          poetry version ${{ env.PATCH_VERSION }}

      - name: Setup global Git configs
        run: |
          git config --global user.name "DevOps" #TODO: ${{ vars.GITHUB_DEVOPS_USERNAME_VAR }}
          git config --global user.email "DevOps@users.noreply.github.com" #TODO: ${{ vars.GITHUB_DEVOPS_EMAIL_VAR }}

      - name: Initial patch version on hotfix branch
        run: |
          git checkout -b "hotfix/v${{ env.PATCH_VERSION }}"
          git commit -am "chore: :bookmark: Release hotfix version v${{ env.PATCH_VERSION }})"
          git push -u origin "hotfix/v${{ env.PATCH_VERSION }}"