name: reusable-workflow-sync-databricks-repo

on:
  workflow_call:
    inputs:
      repository:
          type: string
          description: Repository name
          required: true
      ref:
          type: string
          description: Branch name
          required: true

# Use the Bash shell as default settings for all jobs in the workflow
defaults:
  run:
    shell: bash

jobs:
  sync-databricks-repo:
    name: Sync Databricks Repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch of DevSecOps repository
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.DEVSECOPS_REPOSITORY_VAR }}
          ref: main
          fetch-depth: 0

      - name: Load environment variables from dev dotenv file
        run: |
          cat ./dotenv/dev.env >> $GITHUB_ENV

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Connect to Databricks with Frmwk profiles
        run: |
          echo ${{ secrets.AZURE_DATABRICKS_PAT }} | \
            databricks configure --profile ar-frmwk --host ${{ env.DATABRICKS_HOST }} --token #TODO: ${{ vars.DATABRICKS_PROFILE }}

      - name: Update the repo to the latest commit on ${{ inputs.ref }} branch
        run: |
          databricks --profile ar-frmwk repos update --path /Repos/${{ inputs.repository }} --branch ${{ inputs.ref }} #TODO: ${{ vars.DATABRICKS_PROFILE }} #TODO: ${{ vars.DATABRICKS_PROFILE }}
