name: reusable-workflow-sync-databricks-repo

on:
  workflow_call:
    inputs:
      secret1:
          type: string
          description: Repository name
          required: true

# Use the Bash shell as default settings for all jobs in the workflow
defaults:
  run:
    shell: bash

jobs:
  sync-databricks-repo:
    name: Sync Databricks Repo
    runs-on: ubuntu-latest

    steps:
      - name: run test
        run: curl -vX GET -u "__token__:${{ secrets.SECRET1 }}" "https://dev.azure.com/nakesittipong/fordemoOnly/_apis/wit/workitems?ids={40}&api-version=7.1-preview.3"

